### ISSUE TITLE
Organize configuration files by using sections

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#1611]
Organize configuration files by using sections. 

For example instead of this:
```
guild-tnt-protection-enabled: false
guild-tnt-protection-global: false
guild-tnt-protection-start-time: '22:00'
guild-tnt-protection-end-time: 06:00
```
would be:
```
guild-tnt-protection:
    enabled: false
    global: false
    start-time: 22:00
    end-time: 06:00
```

Unfortunately, it will completely breaks backwards compatibility with older configuration files so...
