### ISSUE TITLE
Stały bossbar/actionbar ma terenie wrogiej gildii

### ISSUE THREAD

**Issue by eskabal** [FunnyGuilds/FunnyGuilds#2051]
przydało by sie dodac ogolnie ze jak wejdziesz na teren gildii lub jakis oponent to na stałe pisze ci na actionbar  i bossbar jestes na terenie gildii mozna tez dodac tkzw metry  czyli odleglosc do jajka np jestes na terenie test (3m) 
![Bez tytułusf](https://user-images.githubusercontent.com/25277653/177754900-508ac9a3-5096-45f8-b515-78c582b33936.png)
bo tak troche lipa jak pojdzie sie ktos klepac i bedzie musiał wchodzic i wychodzic by sie dowiedziec jaka to gildia
a do bossbara mozna by było na te wyzsze wersje dodac update paska w dol  czyli jak sie oddalasz od g pasek idzie w dol a jak sie zblizasz w gore

**Comment by dzikoysk** [comment]
W pliku `pl.yml` możesz zmieć wartość `stay` na `-1`:

```yml
notificationEnterGuildRegion:
  actionbar: '&7Wkroczyles na teren gildii &c{TAG}&7!'
  bossbar:
    name: '&7Wkroczyles na teren gildii &c{TAG}&7!'
    color: RED
    overlay: PROGRESS
    flags:
    - CREATE_WORLD_FOG
    progress: 1.0
    stay: 300
    clear-other-bars: true
```
