### ISSUE TITLE
Zmienić serializowanie/deserializowanie ItemStack'ów w configu

### ISSUE THREAD

**Issue by P3ridot** [FunnyGuilds/FunnyGuilds#2344]
Aktualnie pakujemy wszystko w 1 stringa -> `item: '1 diamond name:FunnyGuilds lore:Amazing_plugin'`

A powinniśmy to wymienić na serializowanie jako obiekt:

```yaml
item:
  material: diamond
  count: 1
  name: FunnyGuilds
  lore: Amazing plugin
```
